# Generated by Django 2.0 on 2018-02-12 06:59

import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion
import voters.models.base
import voters.models.districts
from django.contrib.postgres.operations import CryptoExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CryptoExtension(),
        migrations.CreateModel(
            name='CongressionalDistrict',
            fields=[
                ('abbrv', voters.models.base.VoterCharField(help_text='Assigned by the election authority.', max_length=6, primary_key=True, serialize=False, voter_column_name='cong_dist_abbrv')),
                ('description', voters.models.base.VoterCharField(max_length=60, voter_column_name='cong_dist_abbrv')),
            ],
            bases=(models.Model, voters.models.districts.DistrictModelMixin),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', voters.models.base.VoterSmallIntegerField(help_text='Assigned by election authority.', primary_key=True, serialize=False, voter_column_name='county_id')),
                ('description', voters.models.base.VoterCharField(max_length=15, voter_column_name='county_desc')),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
            bases=(models.Model, voters.models.districts.DistrictModelMixin),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID(), editable=False, help_text='Randomly generated universal unique identifier.', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StateHouseDistrict',
            fields=[
                ('abbrv', voters.models.base.VoterCharField(help_text='Assigned by the election authority.', max_length=6, primary_key=True, serialize=False, voter_column_name='nc_house_abbrv')),
                ('description', voters.models.base.VoterCharField(max_length=60, voter_column_name='nc_house_abbrv')),
            ],
            bases=(models.Model, voters.models.districts.DistrictModelMixin),
        ),
        migrations.CreateModel(
            name='StateSenateDistrict',
            fields=[
                ('abbrv', voters.models.base.VoterCharField(help_text='Assigned by the election authority.', max_length=6, primary_key=True, serialize=False, voter_column_name='nc_senate_abbrv')),
                ('description', voters.models.base.VoterCharField(max_length=60, voter_column_name='nc_senate_abbrv')),
            ],
            bases=(models.Model, voters.models.districts.DistrictModelMixin),
        ),
        migrations.CreateModel(
            name='SuperiorCourtDistrict',
            fields=[
                ('abbrv', voters.models.base.VoterCharField(help_text='Assigned by the election authority.', max_length=6, primary_key=True, serialize=False, voter_column_name='super_court_abbrv')),
                ('description', voters.models.base.VoterCharField(max_length=60, voter_column_name='super_court_abbrv')),
            ],
            bases=(models.Model, voters.models.districts.DistrictModelMixin),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('ncid', voters.models.base.VoterCharField(db_index=True, help_text='Assigned by election authority.', max_length=12, primary_key=True, serialize=False, verbose_name='ncid', voter_column_name='ncid')),
                ('birth_age', voters.models.base.VoterIntegerField(voter_column_name='birth_age')),
                ('birth_year', voters.models.base.VoterIntegerField(null=True, voter_column_name='birth_year')),
                ('confidential_ind', voters.models.base.VoterBooleanField(voter_column_name='confidential_ind')),
                ('birth_state', voters.models.base.VoterCharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('UM', 'U.S. Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands')], max_length=2, verbose_name='birth state', voter_column_name='birth_state')),
                ('voter_reg_num', voters.models.base.VoterCharField(max_length=12, voter_column_name='voter_reg_num')),
                ('status_cd', voters.models.base.VoterCharField(max_length=2, voter_column_name='status_cd')),
                ('voter_status_desc', voters.models.base.VoterCharField(max_length=25, voter_column_name='voter_status_desc')),
                ('reason_cd', voters.models.base.VoterCharField(max_length=2, voter_column_name='reason_cd')),
                ('voter_status_reason_desc', voters.models.base.VoterCharField(max_length=60, voter_column_name='voter_status_reason_desc')),
                ('name_prefx_cd', voters.models.base.VoterCharField(max_length=4, voter_column_name='name_prefx_cd')),
                ('last_name', voters.models.base.VoterCharField(max_length=25, voter_column_name='last_name')),
                ('middle_name', voters.models.base.VoterCharField(max_length=25, voter_column_name='middle_name')),
                ('first_name', voters.models.base.VoterCharField(max_length=20, voter_column_name='first_name')),
                ('name_suffix_lbl', voters.models.base.VoterCharField(max_length=30, voter_column_name='name_suffix_lbl')),
                ('midl_name', voters.models.base.VoterCharField(max_length=20, voter_column_name='midl_name')),
                ('name_sufx_cd', voters.models.base.VoterCharField(max_length=3, voter_column_name='name_sufx_cd')),
                ('res_street_address', voters.models.base.VoterCharField(max_length=63, voter_column_name='res_street_address')),
                ('res_city_desc', voters.models.base.VoterCharField(max_length=60, voter_column_name='res_city_desc')),
                ('state_cd', voters.models.base.VoterCharField(max_length=2, voter_column_name='state_cd')),
                ('zip_code', voters.models.base.VoterCharField(max_length=9, voter_column_name='zip_code')),
                ('mail_addr1', voters.models.base.VoterCharField(max_length=40, voter_column_name='mail_addr1')),
                ('mail_addr2', voters.models.base.VoterCharField(max_length=40, voter_column_name='mail_addr2')),
                ('mail_addr3', voters.models.base.VoterCharField(max_length=40, voter_column_name='mail_addr3')),
                ('mail_addr4', voters.models.base.VoterCharField(max_length=40, voter_column_name='mail_addr4')),
                ('mail_city', voters.models.base.VoterCharField(max_length=30, voter_column_name='mail_city')),
                ('mail_state', voters.models.base.VoterCharField(max_length=2, voter_column_name='mail_state')),
                ('mail_zipcode', voters.models.base.VoterCharField(max_length=9, voter_column_name='mail_zipcode')),
                ('full_phone_number', voters.models.base.VoterCharField(max_length=12, voter_column_name='full_phone_number')),
                ('race_code', voters.models.base.VoterCharField(choices=[('B', 'African American/Black'), ('A', 'Asian'), ('I', 'American Indian/Alaska Native'), ('M', 'Multiracial'), ('O', 'Other'), ('U', 'Undesignated'), ('W', 'White')], max_length=3, voter_column_name='race_code')),
                ('ethnic_code', voters.models.base.VoterCharField(choices=[('HL', 'Hispanic/Latino'), ('NL', 'Not Hispanic/Latino'), ('UN', 'Undesignated')], max_length=3, voter_column_name='ethnic_code')),
                ('party_cd', voters.models.base.VoterCharField(choices=[('DEM', 'Democrat'), ('LIB', 'Libertarian'), ('REP', 'Republican'), ('UNA', 'Unaffiliated')], max_length=3, voter_column_name='party_cd')),
                ('gender_code', voters.models.base.VoterCharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undesignated')], max_length=1, voter_column_name='gender_code')),
                ('birth_place', voters.models.base.VoterCharField(max_length=30, voter_column_name='birth_place')),
                ('drivers_lic', voters.models.base.VoterBooleanField(voter_column_name='drivers_lic')),
                ('registr_dt', voters.models.base.VoterDateField(voter_column_name='registr_dt')),
                ('congressional', voters.models.base.VoterForeignKey(db_column='congressional_district_abbrv', help_text='Refers to the congressional district in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.CongressionalDistrict', voter_column_name='congressional')),
                ('county', voters.models.base.VoterForeignKey(help_text='Refers to the county in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.County', voter_column_name='county')),
                ('state_house', voters.models.base.VoterForeignKey(db_column='state_house_district_abbrv', help_text='Refers to the state house district in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.StateHouseDistrict', voter_column_name='state_house')),
                ('state_senate', voters.models.base.VoterForeignKey(db_column='state_senate_district_abbrv', help_text='Refers to the state senate district in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.StateSenateDistrict', voter_column_name='state_senate')),
                ('superior_court', voters.models.base.VoterForeignKey(db_column='superior_court_district_abbrv', help_text='Refers to the superior court in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.SuperiorCourtDistrict', voter_column_name='superior_court')),
            ],
        ),
        migrations.CreateModel(
            name='VoterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_reg_num', models.CharField(blank=True, max_length=12)),
                ('voting_method', models.CharField(blank=True, max_length=32)),
                ('voted_party_cd', models.CharField(blank=True, max_length=3)),
                ('county_id', models.SmallIntegerField(db_index=True)),
                ('voted_county_id', models.SmallIntegerField()),
                ('election', models.ForeignKey(help_text='Refers to the election in which the vote was cast.', on_delete=django.db.models.deletion.CASCADE, to='voters.Election')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='voters.Voter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together={('date', 'name')},
        ),
    ]
