# Generated by Django 2.0 on 2018-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='race_code',
            field=models.CharField(choices=[('A', 'ASIAN'), ('B', 'BLACK'), ('I', 'INDIAN AMERICAN'), ('M', 'MULTI-RACIAL'), ('O', 'OTHER'), ('U', 'UNDESIGNATED'), ('W', 'WHITE')], max_length=3, verbose_name='race_code'),
        ),
    ]
