# Generated by Django 2.0 on 2018-02-12 08:36

from django.db import migrations, models
import django.db.models.deletion
import voters.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionNameTranslator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clean_name', models.CharField(max_length=100)),
                ('raw_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='congressional',
            field=voters.models.base.VoterForeignKey(db_column='congressional_district_abbrv', help_text='Refers to the congressional district in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.CongressionalDistrict', voter_column_name='cong_dist_abbrv'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='county',
            field=voters.models.base.VoterForeignKey(help_text='Refers to the county in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.County', voter_column_name='county_id'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state_house',
            field=voters.models.base.VoterForeignKey(db_column='state_house_district_abbrv', help_text='Refers to the state house district in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.StateHouseDistrict', voter_column_name='nc_house_abbrv'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state_senate',
            field=voters.models.base.VoterForeignKey(db_column='state_senate_district_abbrv', help_text='Refers to the state senate district in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.StateSenateDistrict', voter_column_name='nc_senate_abbrv'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='superior_court',
            field=voters.models.base.VoterForeignKey(db_column='superior_court_district_abbrv', help_text='Refers to the superior court in which the voter resides.', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.SuperiorCourtDistrict', voter_column_name='super_court_abbrv'),
        ),
    ]
