# Generated by Django 2.0 on 2018-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_auto_20180122_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='ethnic_code',
            field=models.CharField(choices=[('HL', 'Hispanic/Latino'), ('NL', 'Not Hispanic/Latino'), ('UN', 'Undesignated')], max_length=3, verbose_name='ethnic_code'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender_code',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undesignated')], max_length=1, verbose_name='gender_code'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party_cd',
            field=models.CharField(choices=[('DEM', 'Democrate'), ('LIB', 'Libertarian'), ('REP', 'Republican'), ('UNA', 'Unaffiliated')], max_length=3, verbose_name='party_cd'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='race_code',
            field=models.CharField(choices=[('B', 'African American/Black'), ('A', 'Asian'), ('I', 'American Indian/Alaska Native'), ('M', 'Multiracial'), ('O', 'Other'), ('U', 'Undesignated'), ('W', 'White')], max_length=3, verbose_name='race_code'),
        ),
    ]
